name: Deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn --immutable
      - name: Build
        run: yarn build
      - name: Vercel pull
        run: yarn vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Vercel build
        run: yarn vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Vercel deploy
        run: |
          echo "Deploying branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            yarn vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          fi
      - name: Deploy failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Deploy failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deploy cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: Deploy cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
