name: Lint

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn --immutable
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Lint failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Lint failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Lint cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: Lint cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

env:
  CI: true
